version: '3.4'

services:
    mongodb:
        build:
          context: .
        ports:
          - "30001:27017"
        command: [--auth]
        volumes:
          - ./db:/data/db
          - ./script/:/docker-entrypoint-initdb.d/
        environment:
          - MONGO_INITDB_ROOT_USERNAME=admin
          - MONGO_INITDB_ROOT_PASSWORD=admin123
        restart: always