version: '3.4'

services:
    primary:
      build:
        context: .
      networks:
        static-network:
          ipv4_address: 192.168.7.101
      ports:
        - "30001:27017"
      command: ["--bind_ip", "192.168.7.101", "--logpath", "/data/logs/mongod.log", "--replSet", "grpc"]
      environment:
        - MONGO_INITDB_ROOT_USERNAME=admin
        - MONGO_INITDB_ROOT_PASSWORD=admin123
      volumes:
        - ./script/create_user.js:/create_user.js
        - ./script/replicaset.js:/replicaset.js
        #- ./hosts/hosts:/etc/hosts
        - ./db01:/data/db
      restart: always
    
    secondary:
      build:
        context: .
      networks:
        static-network:
          ipv4_address: 192.168.7.102
      depends_on:
        - primary
      ports:
        - "30002:27017"
      command: ["--bind_ip", "192.168.7.102", "--logpath", "/data/logs/mongod.log", "--replSet", "grpc"]
      volumes:
        #- ./hosts/hosts:/etc/hosts
        - ./db02:/data/db
      restart: always
    
    arbiter:
      build:
        context: .
      networks:
        static-network:
          ipv4_address: 192.168.7.103
      depends_on:
        - primary
      ports:
        - "30003:27017"
      command: ["--bind_ip", "192.168.7.103", "--logpath", "/data/logs/mongod.log", "--replSet", "grpc"]
      volumes:
        #- ./hosts/hosts:/etc/hosts
        - ./db03:/data/db
      restart: always

networks:
  static-network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.7.0/24
